name: Documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  update_documentation:
    name: Update documentation
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Setup Swift version
        uses: swift-actions/setup-swift@v2.2.0
        with:
          swift-version: "5.10"
      - name: Generate documentation
        uses: fwcd/swift-docc-action@v1.0.2
        with:
          target: Boutique
          output: ./docs
          hosting-base-path: Boutique
          disable-indexing: 'true'
          transform-for-static-hosting: 'true'
      - name: Commit documentation
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./docs/**
          git commit -m "Generating documentation"
          git push

